"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FIXPR_ENVIRONMENT_VARIABLES = exports.BLACKDUCK_SCAN_FAILURE_SEVERITIES = void 0;
var BLACKDUCK_SCAN_FAILURE_SEVERITIES;
(function (BLACKDUCK_SCAN_FAILURE_SEVERITIES) {
    BLACKDUCK_SCAN_FAILURE_SEVERITIES["ALL"] = "ALL";
    BLACKDUCK_SCAN_FAILURE_SEVERITIES["NONE"] = "NONE";
    BLACKDUCK_SCAN_FAILURE_SEVERITIES["BLOCKER"] = "BLOCKER";
    BLACKDUCK_SCAN_FAILURE_SEVERITIES["CRITICAL"] = "CRITICAL";
    BLACKDUCK_SCAN_FAILURE_SEVERITIES["MAJOR"] = "MAJOR";
    BLACKDUCK_SCAN_FAILURE_SEVERITIES["MINOR"] = "MINOR";
    BLACKDUCK_SCAN_FAILURE_SEVERITIES["OK"] = "OK";
    BLACKDUCK_SCAN_FAILURE_SEVERITIES["TRIVIAL"] = "TRIVIAL";
    BLACKDUCK_SCAN_FAILURE_SEVERITIES["UNSPECIFIED"] = "UNSPECIFIED";
})(BLACKDUCK_SCAN_FAILURE_SEVERITIES = exports.BLACKDUCK_SCAN_FAILURE_SEVERITIES || (exports.BLACKDUCK_SCAN_FAILURE_SEVERITIES = {}));
exports.FIXPR_ENVIRONMENT_VARIABLES = {
    GITHUB_TOKEN: 'GITHUB_TOKEN',
    GITHUB_REPOSITORY: 'GITHUB_REPOSITORY',
    GITHUB_HEAD_REF: 'GITHUB_HEAD_REF',
    GITHUB_REF: 'GITHUB_REF',
    GITHUB_REF_NAME: 'GITHUB_REF_NAME',
    GITHUB_REPOSITORY_OWNER: 'GITHUB_REPOSITORY_OWNER'
};
